services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: messenger_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789Bb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:latest 
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"   
      - "15672:15672"  
    environment:
      RABBITMQ_DEFAULT_USER: admin@admin.com
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - backend

  web:
    build: .
    restart: always
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - backend

  celery:
    build: .
    command: celery -A messenger worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env.local
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - backend

volumes:
  postgres_data:
  pgadmin_data:

networks:
  backend:
