# Generated by Django 5.2.1 on 2025-05-10 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phoneotp',
            unique_together=set(),
        ),
    ]
